version: "3"
services:
  app:
    build: .
    image: rhull12345/rivereyes:app1.0
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'rivereyes'
      MYSQL_PASSWORD : 'root'
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'rivereyes'
      MYSQL_PASSWORD : 'root'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    # command: mysql --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"USE rivereyes; SELECT * FROM usgs_gages;\""
      interval: 15s
      timeout: 30s
      retries: 80


